name: analytics_logger_gen_example
description: Demonstrates how to use the analytics_logger_gen plugin.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  analytics_logger_gen:
    path: ../
  cupertino_icons: ^1.0.2
  firebase_core: ^2.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  firebase_analytics: ^10.2.0
  appsflyer_sdk: ^6.9.3
  amplitude_flutter: ^3.14.0
  mixpanel_flutter: ^2.1.1
  singular_flutter_sdk: ^1.0.13
  datadog_flutter: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
