name: analytics_logger_gen
description: analytics_logger_gen is a Flutter plugin that generates an integrated event logger for various analytics tools including Firebase, AppsFlyer, Amplitude, Mixpanel, Singular, and DataDog. Import data from Google Spreadsheets, remote repositories, or local CSV files.
version: 1.0.0
homepage: https://github.com/9oya
repository: https://github.com/9oya/analytics_logger_gen
issue_tracker: https://github.com/9oya/analytics_logger_gen/issues

platforms:
  linux:
  macos:
  windows:

environment:
  sdk: '>=2.18.6 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  analyzer: ^4.7.0
  build: ^2.3.1
  source_gen: ^1.2.6
  http: ^0.13.5
  path: ^1.8.0
  csv: ^5.0.1
  change_case: ^1.1.0

dev_dependencies:
  build_runner: ^2.3.3
  build_test:
  test: ^1.0.0

flutter: